= Verbs

== Introduction

Verbs in conlang1 conjugate with person and number. Conlang1 is a pro-drop language.

Verbs can be conjugated for 3 persons, 2 numbers, and present and preterite tenses. The non-conjugated forms include:

- the infinitive--usually with the same stem as the present conjugations,
- the past infinitive--always with the same stem as the past conjugations and meaning "`to have done`",
- the active participle,
- the passive participle.

There are two main types of verbs: strong verbs and weak verbs. They differ in the preterite construction. Strong verbs have vowel alternations. Weak verbs have a dental suffix.

There are some irregular verbs.

The present conjugations vary in number and person. For both weak and strong verbs, the present tense endings are:

.Present tense suffixes

|===
| Person, Sg. | Suffix | Person, Pl. | Suffix

| 1st. | -ẘ | 1st. | -m̊
| 2nd. | -s̊ | 2nd. | -d̥
| 3rd. | -t̊ | 3rd. | -n̊
|===

The preterites of weak verbs have the following suffixes:

.Past tense weak-verb suffixes

|===
| Person, Sg. | Suffix | Person, Pl. | Suffix

| 1st. | -d̥ | 1st. | -dm̊
| 2nd. | -ds̊ | 2nd. | -dd̥
| 3rd. | -d̥ | 3rd. | -dn̊
|===

.Past tense strong-verb suffixes

The preterites of strong verbs have the following suffixes:
|===
| Person, Sg. | Suffix | Person, Pl. | Suffix

| 1st. | - | 1st. | -m̊
| 2nd. | -s̊ | 2nd. | -d̥
| 3rd. | - | 3rd. | -n̊
|===

The preterite of strong verbs have the same suffixes are the present.
