= Verbs

== Introduction

Verbs in Þeudisk-H conjugate with person and number. Þeudisk-H is a mild pro-drop language.

Verbs can be conjugated for 3 persons, 2 numbers, and present and preterite tenses. The non-conjugated forms include:

- the present infinitive--usually with the same stem as the present conjugations,
- the past infinitive--always with the same stem as the past conjugations and meaning "`to have done`",
- the active participle,
- the passive participle.

There are two main types of verbs: *strong verbs* and *weak verbs*. They differ in the preterite construction. Strong verbs have vowel alternations. Weak verbs have a dental suffix.

There are some *irregular verbs* and *preterite-present* verbs.

The present conjugations vary in number and person. For both weak and strong verbs, the present tense endings are:

.Present tense suffixes

[cols="s,1,s,1"]
|===
| Singular | Suffix | Plural | Suffix

| 1st. | -ĕw | 1st. | -ĕm
| 2nd. | -ĕs | 2nd. | -ĕj
| 3rd. | -ĕt | 3rd. | -ĕn
|===

The preterites of weak verbs have the following suffixes:

.Past tense weak-verb suffixes

[cols="s,1,s,1"]
|===
| Singular | Suffix | Plural | Suffix

| 1st. | -ĕd  | 1st. | -dĕm
| 2nd. | -dĕs | 2nd. | -dĕj
| 3rd. | -ĕd  | 3rd. | -dĕn
|===

The preterites of strong verbs have the following suffixes:

.Past tense strong-verb suffixes

[cols="s,1,s,1"]
|===
| Singular | Suffix | Plural | Suffix

| 1st. | -   | 1st. | -ĕm
| 2nd. | -ĕs | 2nd. | -ĕj
| 3rd. | -   | 3rd. | -ĕn
|===
