= Pronouns, articles, and determiners

Pronouns, articles, and determiners are tightly intertwined.

In Þeudisk-H, all nouns are accompanied by a determiner.
A consequence of this is that the grammatical case for any noun (or pronoun)
is almost always known.

The determiner can be default the (unmarked) definite and indefinite articles,
or be:

- a demostrative,
- a possessive pronoun,
- quantifiers e.g. all / none / numbers.

== First-person and second-person pronouns

|===
| | Nominative | Oblique | Genitive

s| 1 sg.  | ek | mih | mín
s| 2 sg.  | þu | þih | þín
s| 1 pl.  | we | ons | onzr
s| 2 pl.  | je | joh | jór
|===

== Articles and demostratives

The definite articles are:

|===
| | Nominative | Oblique | Genitive

h| Sg. | þe  | þen | þes
h| Pl. | þej | þem | þer
|===

The indefinite articles are:

|===
| | Nominative | Oblique | Genitive

h| Sg. | en  | enĕn | enĕs
h| Pl. | enĕj | enĕm | enĕr
|===

The demostratives are:

|===
| | Nominative | Oblique | Genitive

h| Sg. prox.   | þit | þizĕn | þizĕs
h| Sg. medial  | þat | þazĕn | þazĕs
h| Sg. distal  | jet | jenĕn | jenĕs

h| Pl. close   | þizĕj | þizĕm | þizĕr
h| Pl. medial  | þazĕj | þazĕm | þazĕr
h| Pl. distal  | jenĕj | jenĕm | jenĕr
|===

All articles and demostratives can be used as pronouns.

The third person _personal_ pronouns are used when a subject is human, or is
personified.

|===
| | Nom. | Obl. | Gen.

h| Sg. m. | he  | hem | hes
h| Sg. f. | se  | sem | ses
h| Pl.    | þej | þem | þer
|===

All third person pronouns, including demostrative pronouns, have special
"`reflexive`" oblique and genitive forms:

Reflexive oblique:: sih
Genitive oblique:: sín

== Dummy pronoun

The dummy pronoun "`er`" is used as dummy subject for constructions like "there is", descriptions about weather, temperature.

== Interrogative and relative pronouns

Interrogative pronouns function as relative pronouns too.

[cols="1,1,1,e"]
|===
| Nom. | Obl. | Gen. | Meaning

| hwe | hwem | hwes | who
| hwa | hwat | hwas | what
| hwelk | hwelkt | hwelks | which
|===

Examples:

- "`Hwe is þe küning?`" (_Who is the king?_)
- "`Hwem sehs þu?`" (_Whom do you see?_)
- "`Þe knav hwe lefd.`" (_The boy who lived._)
- "`Þe magþ hwem þej sah.`" (_The girl whom they saw._)
- "`Af þen hwilkt flód drank þe wolf.`" (_From which river did the wolf drink?_)
- "`Þen hwilks sung hördĕd je?`" (_Of which one, do y'all hear the song?_)

== Pro-adverbs

[cols="1,e"]
|===
| Adverb | Meaning

| hwor | where
| hwan | when
| hwis | how
|===

Pro-adverbs may be combined with prepositions (like in English: _whence_, _whereto_),
and this preposition is separable.

Prepositional relative pronouns with _hwan_:

- hwantil (_until when_)
- hwanaf (_since when_)

Examples:

- Hwan is þín borsdag? (_When is your birthday?_)
- Hwan kokm we af? (_When do we start cooking?_)
- Hwan hweint þet til? (_Until when does it cry?_)
- Þe dag hwan we ranm. (_The day when we ran._)
- Þe dag hwanaf þe kind hleip (_The day whence the child walked._)
- Þe dag hwantil þej skaln stop mid flæsk etan (_The day until which they will stop eating meat._)
