= Verbs

== Introduction

Verbs in conlang1 conjugate with person and number. Conlang1 is a pro-drop language.

Verbs can be conjugated for 3 persons, 2 numbers, and present and preterite tenses. The non-conjugated forms include:

- the infinitive--usually with the same stem as the present conjugations,
- the past infinitive--always with the same stem as the past conjugations and meaning "`to have done`",
- the active participle,
- the passive participle.

There are two main types of verbs: strong verbs and weak verbs. They differ in the preterite construction. Strong verbs have vowel alternations. Weak verbs have a dental suffix.

There are some irregular verbs.

The present conjugations vary in number and person. For both weak and strong verbs, the present tense endings are:

.Present tense suffixes
|===
| Person, Sg. | Suffix | Person, Pl. | Suffix

| 1st. | -w | 1st. | -m
| 2nd. | -s | 2nd. | -d
| 3rd. | -þ | 3rd. | -n
|===

The preterites of weak verbs have the following suffixes:

.Past tense weak-verb suffixes
|===
| Person, Sg. | Suffix | Person, Pl. | Suffix

| 1st. | -du | 1st. | -dum
| 2nd. | -dus | 2nd. | -dud
| 3rd. | -du | 3rd. | -dun
|===

.Past tense strong-verb suffixes
The preterites of strong verbs have the following suffixes:
|===
| Person, Sg. | Suffix | Person, Pl. | Suffix

| 1st. | - | 1st. | -m
| 2nd. | -s | 2nd. | -d
| 3rd. | - | 3rd. | -n
|===

The preterite of strong verbs have the same suffixes are the present.

== Main types of verbs

=== Strong verbs

More info: https://en.wiktionary.org/wiki/Category:Proto-Germanic_strong_verbs


=== Weak verbs

## Rückumlaut verbs

Rückumlaut verbs are weak verbs that exhibit a vowel change in the stem in the preterite form. They derive from Proto-Germanic -ijaną  verbs. Some of them are causative verbs, as in English "fell" i.e. to cause to fall.

Some causative verbs derived from other verbs are:

| Class | Origin  | Class | Caus. Present | Caus. Past | Meaning    |
|:------|:--------|:------|:--------------|:-----------|:-----------|
| S 1   | leiðan  | W 1   | laiðan        |            | to undergo |
| S 5 j | li      | W 1   | laiðan        |            | to undergo |
| S 6   | wakan   | W 1   | wæken         | wakt       | to wake    |
| S 6   | brinnan | W 1   | brænnan       | brand-     | to burn    |

| Present | Past   | Participle | Meaning  | Notes      |
|:--------|:-------|:-----------|:---------|:-----------|
| bringan | bragdu |            | to bring |            |
| telan   | taldu  |            |          |            |
| þenkan  | þahtu  |            | to think |            |
| fregan  | frahdu |            | to ask   | HG. fragen |
| segan   | sagdu  |            |          |            |
| sendan  | sanddu |            |          |            |

## Common verbs

